export const WILAYAS = [
  { code: "01", ar: "أدرار", fr: "Adrar" },
  { code: "02", ar: "الشلف", fr: "Chlef" },
  { code: "03", ar: "الأغواط", fr: "Laghouat" },
  { code: "04", ar: "أم البواقي", fr: "Oum El Bouaghi" },
  { code: "05", ar: "باتنة", fr: "Batna" },
  { code: "06", ar: "بجاية", fr: "Béjaïa" },
  { code: "07", ar: "بسكرة", fr: "Biskra" },
  { code: "08", ar: "بشار", fr: "Béchar" },
  { code: "09", ar: "البليدة", fr: "Blida" },
  { code: "10", ar: "البويرة", fr: "Bouira" },
  { code: "11", ar: "تمنراست", fr: "Tamanrasset" },
  { code: "12", ar: "تبسة", fr: "Tébessa" },
  { code: "13", ar: "تلمسان", fr: "Tlemcen" },
  { code: "14", ar: "تيارت", fr: "Tiaret" },
  { code: "15", ar: "تيزي وزو", fr: "Tizi Ouzou" },
  { code: "16", ar: "الجزائر", fr: "Alger" },
  { code: "17", ar: "الجلفة", fr: "Djelfa" },
  { code: "18", ar: "جيجل", fr: "Jijel" },
  { code: "19", ar: "سطيف", fr: "Sétif" },
  { code: "20", ar: "سعيدة", fr: "Saïda" },
  { code: "21", ar: "سكيكدة", fr: "Skikda" },
  { code: "22", ar: "سيدي بلعباس", fr: "Sidi Bel Abbès" },
  { code: "23", ar: "عنابة", fr: "Annaba" },
  { code: "24", ar: "قالمة", fr: "Guelma" },
  { code: "25", ar: "قسنطينة", fr: "Constantine" },
  { code: "26", ar: "المدية", fr: "Médéa" },
  { code: "27", ar: "مستغانم", fr: "Mostaganem" },
  { code: "28", ar: "المسيلة", fr: "M'Sila" },
  { code: "29", ar: "معسكر", fr: "Mascara" },
  { code: "30", ar: "ورقلة", fr: "Ouargla" },
  { code: "31", ar: "وهران", fr: "Oran" },
  { code: "32", ar: "البيض", fr: "El Bayadh" },
  { code: "33", ar: "إليزي", fr: "Illizi" },
  { code: "34", ar: "برج بوعريريج", fr: "Bordj Bou Arréridj" },
  { code: "35", ar: "بومرداس", fr: "Boumerdès" },
  { code: "36", ar: "الطارف", fr: "El Tarf" },
  { code: "37", ar: "تندوف", fr: "Tindouf" },
  { code: "38", ar: "تيسمسيلت", fr: "Tissemsilt" },
  { code: "39", ar: "الوادي", fr: "El Oued" },
  { code: "40", ar: "خنشلة", fr: "Khenchela" },
  { code: "41", ar: "سوق أهراس", fr: "Souk Ahras" },
  { code: "42", ar: "تيبازة", fr: "Tipaza" },
  { code: "43", ar: "ميلة", fr: "Mila" },
  { code: "44", ar: "عين الدفلى", fr: "Aïn Defla" },
  { code: "45", ar: "النعامة", fr: "Naâma" },
  { code: "46", ar: "عين تيموشنت", fr: "Aïn Témouchent" },
  { code: "47", ar: "غرداية", fr: "Ghardaïa" },
  { code: "48", ar: "غليزان", fr: "Relizane" },
];

export const BLOOD_TYPES = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const SPECIALTIES_AR = [
  "طب عام",
  "أمراض النساء والتوليد",
  "طب الأطفال",
  "طب القلب والأوعية الدموية",
  "طب العظام والمفاصل",
  "طب الأسنان",
  "طب العيون",
  "طب الأنف والأذن والحنجرة",
  "طب الجلد والتجميل",
  "طب الجهاز الهضمي",
  "طب الأعصاب",
  "طب الصدر والجهاز التنفسي",
  "طب النفسي",
  "طب الكلى",
  "الجراحة العامة",
  "طب الطوارئ والإسعاف",
];

export const EQUIPMENT_TYPES_AR = [
  "كرسي متحرك",
  "سرير طبي",
  "عكاز / مشاية",
  "جهاز أكسجين",
  "جهاز ضغط",
  "جهاز سكري",
  "أجهزة أخرى",
];

// Sample mock data for offline use
export const SAMPLE_DOCTORS = [
  {
    _id: "doc1",
    name: "د. أمين بن علي",
    specialty: "أمراض النساء والتوليد",
    wilaya: "عنابة",
    wilaya_code: "23",
    address: "عنابة - الحجار",
    phone: "0555 12 34 56",
    fee: 2000,
    rating: 4.9,
    review_count: 280,
    experience_years: 12,
    patients_count: 2800,
    satisfaction: 98,
    is_verified: true,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80",
    lat: 36.9,
    lng: 7.76,
    about:
      "أخصائي في أمراض النساء والتوليد، علاج عقم المرأة، متابعة الحمل، الجراحة بالمنظار، علاج عنق الرحم باليلزر، أمراض الثدي.",
    tags: ["عقم المرأة", "متابعة الحمل", "جراحة المنظار", "عنق الرحم"],
  },
  {
    _id: "doc2",
    name: "د. سامية براج",
    specialty: "طب الأطفال وحديثي الولادة",
    wilaya: "عنابة",
    wilaya_code: "23",
    address: "عنابة - سيدي عمار",
    phone: "0555 23 45 67",
    fee: 1500,
    rating: 4.8,
    review_count: 190,
    experience_years: 9,
    patients_count: 1900,
    satisfaction: 96,
    is_verified: true,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80",
    lat: 36.92,
    lng: 7.77,
    about: "أطفال وحديثي الولادة، متابعة نمو الطفل، التطعيمات.",
    tags: ["حديثي الولادة", "تطعيمات", "نمو الطفل"],
  },
  {
    _id: "doc3",
    name: "د. كريم حمداني",
    specialty: "طب العظام والمفاصل",
    wilaya: "عنابة",
    wilaya_code: "23",
    address: "عنابة - سيدي عمار",
    phone: "0555 34 56 78",
    fee: 2500,
    rating: 4.7,
    review_count: 156,
    experience_years: 15,
    patients_count: 3100,
    satisfaction: 94,
    is_verified: true,
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&q=80",
    lat: 36.91,
    lng: 7.78,
    about: "جراح عظام متخصص في إصابات الركبة والكتف والعمود الفقري.",
    tags: ["إصابات الركبة", "العمود الفقري", "الكتف"],
  },
  {
    _id: "doc4",
    name: "د. وليد زروقي",
    specialty: "طب القلب والأوعية الدموية",
    wilaya: "عنابة",
    wilaya_code: "23",
    address: "عنابة - المدينة",
    phone: "0555 45 67 89",
    fee: 3000,
    rating: 4.6,
    review_count: 120,
    experience_years: 18,
    patients_count: 4200,
    satisfaction: 97,
    is_verified: true,
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&q=80",
    lat: 36.89,
    lng: 7.75,
    about: "قلبيات وأوعية دموية، قسطرة قلبية، ارتفاع الضغط، أمراض الشريان.",
    tags: ["قسطرة قلبية", "ضغط الدم", "الشريان التاجي"],
  },
  {
    _id: "doc5",
    name: "د. نور الدين بوزيد",
    specialty: "طب عام",
    wilaya: "الجزائر",
    wilaya_code: "16",
    address: "الجزائر - بئر مراد رايس",
    phone: "0555 56 78 90",
    fee: 800,
    rating: 4.5,
    review_count: 340,
    experience_years: 7,
    patients_count: 5200,
    satisfaction: 92,
    is_verified: false,
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&q=80",
    lat: 36.74,
    lng: 3.06,
    about: "طبيب عام متخصص في الرعاية الأولية والوقاية.",
    tags: ["رعاية أولية", "وقاية", "أمراض مزمنة"],
  },
];

export const SAMPLE_DONORS = [
  { _id: "d1", name: "متبرع O+", blood_type: "O+", wilaya: "عنابة", phone: "05 55 12 34 56", is_available: true, hide_name: false },
  { _id: "d2", name: "متبرع A+", blood_type: "A+", wilaya: "قسطينة", phone: "05 55 23 45 67", is_available: true, hide_name: false },
  { _id: "d3", name: "متبرع B+", blood_type: "B+", wilaya: "وهران", phone: "05 55 34 56 78", is_available: false, hide_name: false },
  { _id: "d4", name: "متبرع A-", blood_type: "A-", wilaya: "الجزائر", phone: "05 55 45 67 89", is_available: true, hide_name: true },
  { _id: "d5", name: "متبرع AB+", blood_type: "AB+", wilaya: "عنابة", phone: "07 98 76 54 32", is_available: true, hide_name: false },
];

export const SAMPLE_EQUIPMENT = [
  { _id: "e1", type: "كرسي متحرك", condition: "جيدة", wilaya: "عنابة", phone: "05 55 12 34 56" },
  { _id: "e2", type: "سرير طبي", condition: "سيئة", wilaya: "سطيف", phone: "05 55 23 45 67" },
  { _id: "e3", type: "جهاز أكسجين", condition: "جيدة", wilaya: "قسطينة", phone: "05 55 34 56 78" },
];

export const SAMPLE_PHARMACIES = [
  { _id: "p1", name: "صيدلية السلام", address: "عنابة - المدينة", wilaya: "عنابة", phone: "038 11 22 33", on_call_24h: true, night_shift: true, rating: 4.5 },
  { _id: "p2", name: "صيدلية النور", address: "عنابة - وسط المدينة", wilaya: "عنابة", phone: "038 22 33 44", on_call_24h: false, night_shift: true, rating: 4.2 },
  { _id: "p3", name: "صيدلية الأمل", address: "عنابة - البوني", wilaya: "عنابة", phone: "038 33 44 55", on_call_24h: false, night_shift: false, rating: 4.0 },
];

export const SAMPLE_HOSPITALS = [
  { _id: "h1", name: "المستشفى الجامعي عنابة", address: "عنابة - المدينة", wilaya: "عنابة", phone: "038 86 20 05", type: "public", rating: 4.5 },
  { _id: "h2", name: "مستشفى ابن رشد", address: "عنابة - حيدرة", wilaya: "عنابة", phone: "038 87 30 10", type: "private", rating: 4.3 },
  { _id: "h3", name: "عيادة طبي كهرباني", address: "سطيف - وسط المدينة", wilaya: "سطيف", phone: "036 11 22 33", type: "private", rating: 4.1 },
];
